feature_flags:
  registration_closed: false

environment: local

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres

port: 8080

mailer:
  hostname: localhost
  port: 25
  from: administrator@localhost
  password:

blob_url: file:///tmp/teknologi-umum-conference

signature:
  public_key: hex encoded string
  private_key: hex encoded string

validate_payment_key: some string